# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-16 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyers',
            name='email',
            field=models.EmailField(default=0, max_length=254, verbose_name=b'email'),
            preserve_default=False,
        ),
    ]
