# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-16 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0002_buyers_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyers',
            name='birth_date',
            field=models.DateField(verbose_name=b'Birthday'),
        ),
        migrations.AlterField(
            model_name='buyers',
            name='name',
            field=models.CharField(max_length=100, verbose_name=b'Name'),
        ),
        migrations.AlterField(
            model_name='buyers',
            name='surname',
            field=models.CharField(max_length=100, verbose_name=b'Surname'),
        ),
    ]
