# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-17 05:18
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0004_auto_20221117_0502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyers',
            name='checked',
        ),
        migrations.AddField(
            model_name='checkedemail',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='checked', to='sender.Buyers'),
            preserve_default=False,
        ),
    ]
