# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-17 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0005_auto_20221117_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyers',
            name='birth_date',
            field=models.DateTimeField(verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd1\x80\xd0\xbe\xd0\xb6\xd0\xb4\xd0\xb5\xd0\xbd\xd0\xb8\xd1\x8f'),
        ),
    ]
